### PR TITLE
Victory Road: BugFix Variant for Lite Version

### PR DESCRIPTION
**Pull request by wisp92**
This commit only fixes the reset conditions. The puzzle now only resets when the player enters Route 23.

### CODE REVIEW

**Comment by jojobear13** [comment]
>  Due to various evidence I suspect that the puzzle wasn't ment to be reset and this instruction was left for debugging

Can you elaborate more?

**Comment by wisp92** [comment]
There are three peculiar things in this dungeon:
1. First, note that strenth is a must to move towards either end of the dungeon. Specifically moving from Indigo Plateau to Viridian can be done using some shortcut boulders and this is by far the fastest way. So resetting the puzzle after reaching Indigo Plateau only serves as an obstacle to move from Viridian to Indigo Plateau, which by that time there is no need to do. Even reaching Moltres is not affected by this puzzle at all at this point. This is counterintuitive to the reward approach throughout the game. If you reset you don't gain anything at all.
2. Other than the probably misplaced resetting routine in Indigo Plateau Lobby there is also one resetting routine for the first area the moment the player enters the second area. This reset doesn't serve any purpose because of the following: Returning to the first area you can exit through the boulder shortcut much faster than the puzzle's route, and exiting the dungeon it resets the puzzle anyway (assuming the misplaced routine moves back to Route 23). This suggests that this rest was there for testing purposes. Notice also that this kind of routine does not exist in either the first or third area.
3. All resetting routines are conditioned on bit 6 of wCurrentMapScriptFlags. This bit is set after a trainer battle, which might be a debugging method at that time. I couldn't find any other resetting routines conditioned that way.

2) Suggests that the puzzles were meant to either reset on exit or not reset at all, while 1) and 3) point to the second case. What do you think?

**Comment by jojobear13** [comment]
You make good points. I'm starting to think this is a leftover from a beta build of the original red & green versions. The Indigo Plateau went through quite a few changes in development. Maps were redesigned and a half-finished route theme went unused. We are probably seeing old code from a point in development where victory road lead directly into the Indigo lobby area. 

Beta builds were brutal in their difficulty. Routes and dungeons would completely reset upon re-entry including all of the trainers, and the encounter rate was nearly double what we eventually got. I think what we're seeing here with victory road and seafoam islands is an attempt by Gamefreak to tone things down and not make it such a slog. But it was made in haste and only changed just enough to make sure other things didn't break (good ol' game dev crunch).

**Comment by jojobear13** [comment]
closing since I think the other one is snazzier

**Comment by wisp92** [comment]
Thanks for the historic information

**Pull request closed without merging**
